baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'The ACA Price Tracker'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
